"""
Bilingual legal agreement document generator (English + Nepali).
Renders Jinja2 templates stored in the database or falls back to built-in templates.
"""
from jinja2 import Environment, BaseLoader
from app.models.template import LegalDocumentTemplate

# ── BUILT-IN BILINGUAL TEMPLATES PER CATEGORY ─────────────────────────────

_EN_GENERIC = """
RENTAL AGREEMENT

This Rental Agreement ("Agreement") is entered into on {{ agreement_date }} between:

LANDLORD: {{ landlord_name }}, {{ landlord_email }}
TENANT:   {{ tenant_name }}, {{ tenant_email }}

PROPERTY / ASSET DETAILS:
  Category  : {{ rental_category }}
  Asset     : {{ asset_title }}
  Location  : {{ location }}
  Identifier: {{ asset_identifier }}

TERMS:
  Commencement Date : {{ start_date }}
  Termination Date  : {{ end_date }}
  Monthly Rent      : {{ currency }} {{ rent_amount }}
  Payment Due       : 1st of each month

OBLIGATIONS:
1. The Tenant agrees to pay the rent on or before the due date.
2. The Tenant shall maintain the property in good condition.
3. The Landlord shall ensure the property is habitable and free from defects.
4. Either party may terminate this agreement with 30 days written notice.
5. Any damage beyond normal wear and tear shall be the Tenant's responsibility.
6. Sub-letting is not permitted without written consent from the Landlord.

SPECIAL TERMS:
{{ special_terms }}

DIGITAL VERIFICATION:
  Document SHA-256 Hash : {{ document_hash }}
  Verification Code     : {{ verification_code }}
  Platform              : Valid Rent Secure Rental Platform (Academic Prototype)

DISCLAIMER:
This document is generated by the Valid Rent Academic Prototype.
It is NOT an official Government of Nepal document.
"""

_NP_GENERIC = """
भाडा सम्झौता

यो भाडा सम्झौता ("सम्झौता") मिति {{ agreement_date }} मा निम्न पक्षहरू बीच सम्पन्न भएको छ:

घर मालिक: {{ landlord_name }}, {{ landlord_email }}
भाडावाला:  {{ tenant_name }}, {{ tenant_email }}

सम्पत्ति / वस्तुको विवरण:
  वर्ग      : {{ rental_category }}
  वस्तु     : {{ asset_title }}
  स्थान     : {{ location }}
  पहिचान नं.: {{ asset_identifier }}

सर्तहरू:
  सुरु मिति     : {{ start_date }}
  अन्त्य मिति   : {{ end_date }}
  मासिक भाडा    : {{ currency }} {{ rent_amount }}
  भुक्तान मिति  : प्रत्येक महिनाको १ गते

दायित्वहरू:
१. भाडावालाले तोकिएको मितिभित्र भाडा तिर्नु पर्नेछ।
२. भाडावालाले सम्पत्तिलाई राम्रो अवस्थामा राख्नु पर्नेछ।
३. घर मालिकले सम्पत्ति बसोबासयोग्य र दोषमुक्त सुनिश्चित गर्नु पर्नेछ।
४. कुनै पनि पक्षले ३० दिनको लिखित सूचनाद्वारा यो सम्झौता अन्त्य गर्न सक्नेछ।
५. सामान्य टूट-फुटभन्दा बाहिरको क्षतिको जिम्मेवारी भाडावालाको हुनेछ।
६. घर मालिकको लिखित अनुमतिबिना सम्पत्ति अर्कोलाई भाडामा दिन पाइँदैन।

विशेष सर्तहरू:
{{ special_terms }}

डिजिटल प्रमाणीकरण:
  कागजात SHA-256 ह्यास : {{ document_hash }}
  प्रमाणीकरण कोड       : {{ verification_code }}
  प्लेटफर्म             : भ्यालिड रेन्ट सुरक्षित भाडा प्लेटफर्म (शैक्षिक प्रोटोटाइप)

अस्वीकरण:
यो कागजात भ्यालिड रेन्ट शैक्षिक प्रोटोटाइपद्वारा उत्पन्न गरिएको हो।
यो नेपाल सरकारको आधिकारिक कागजात होइन।
"""

_CATEGORY_OVERRIDES = {
    'Land': {
        'en': _EN_GENERIC.replace('PROPERTY / ASSET DETAILS', 'LAND / PLOT DETAILS')
                          .replace('The Tenant shall maintain the property in good condition.',
                                   'The Tenant shall use the land only for agreed purpose.'),
        'np': _NP_GENERIC.replace('सम्पत्ति / वस्तुको विवरण', 'जग्गा / प्लटको विवरण'),
    },
    'Automobile': {
        'en': _EN_GENERIC.replace('PROPERTY / ASSET DETAILS', 'VEHICLE DETAILS')
                          .replace('The Tenant shall maintain the property in good condition.',
                                   'The Tenant shall return the vehicle in its original condition.'),
        'np': _NP_GENERIC.replace('सम्पत्ति / वस्तुको विवरण', 'सवारी साधनको विवरण'),
    },
}


def _render(template_str: str, context: dict) -> str:
    env = Environment(loader=BaseLoader())
    tmpl = env.from_string(template_str)
    return tmpl.render(**context)


def get_template_for_category(category: str) -> tuple[str, str]:
    """Return (en_template, np_template) for the given category."""
    # Check DB first
    db_tmpl = LegalDocumentTemplate.query.filter_by(
        category=category, is_active=True).first()
    if db_tmpl:
        return db_tmpl.template_en, db_tmpl.template_np

    # Fallback to built-in
    override = _CATEGORY_OVERRIDES.get(category)
    if override:
        return override['en'], override['np']
    return _EN_GENERIC, _NP_GENERIC


def generate_bilingual_document(request, agreement=None) -> tuple[str, str]:
    """
    Generate English + Nepali legal text for an agreement request.
    Returns (en_text, np_text).
    """
    from datetime import date
    asset = request.asset

    context = {
        'agreement_date': date.today().strftime('%d %B %Y'),
        'landlord_name': request.landlord.full_name,
        'landlord_email': request.landlord.email,
        'tenant_name': request.tenant.full_name,
        'tenant_email': request.tenant.email,
        'rental_category': request.rental_category,
        'asset_title': asset.asset_title if asset else 'N/A',
        'location': asset.location if asset else 'N/A',
        'asset_identifier': asset.asset_identifier if asset else 'N/A',
        'start_date': str(request.proposed_start_date or 'TBD'),
        'end_date': str(request.proposed_end_date or 'TBD'),
        'currency': request.currency,
        'rent_amount': f"{request.effective_rent:,.2f}" if request.effective_rent else 'TBD',
        'special_terms': request.tenant_message or 'None',
        'document_hash': agreement.document_hash_sha256 if agreement else 'Pending',
        'verification_code': agreement.verification_code if agreement else 'Pending',
    }

    en_tmpl, np_tmpl = get_template_for_category(request.rental_category)
    return _render(en_tmpl, context), _render(np_tmpl, context)
