import os
import hashlib
from datetime import datetime
from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, Image as RLImage, PageBreak, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_JUSTIFY
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

WATERMARK_TEXT = "ACADEMIC PROTOTYPE – NOT AN OFFICIAL GOVERNMENT DOCUMENT"
DISCLAIMER = (
    "This document is generated by the Valid Rent Academic Prototype Platform. "
    "It is NOT affiliated with, endorsed by, or operated by the Government of Nepal. "
    "Any government-style design is used solely for educational demonstration purposes."
)

BLACK = colors.HexColor('#0a0a0a')
DARK  = colors.HexColor('#1e293b')
GOLD  = colors.HexColor('#b45309')
GREEN = colors.HexColor('#15803d')
RED   = colors.HexColor('#dc2626')
GREY  = colors.HexColor('#64748b')
LIGHT = colors.HexColor('#f8fafc')
MID   = colors.HexColor('#e2e8f0')


def _add_watermark(canvas, doc):
    canvas.saveState()
    canvas.setFont('Helvetica-Bold', 18)
    canvas.setFillColorRGB(0.9, 0.9, 0.9)
    canvas.translate(A4[0] / 2, A4[1] / 2)
    canvas.rotate(45)
    canvas.drawCentredString(0, 0, WATERMARK_TEXT)
    canvas.restoreState()


def _page_footer(canvas, doc):
    _add_watermark(canvas, doc)
    canvas.saveState()
    canvas.setFont('Helvetica', 7)
    canvas.setFillColor(GREY)
    canvas.drawString(18 * mm, 10 * mm,
                      f"Valid Rent Platform — Academic Prototype | Nepal")
    canvas.drawCentredString(A4[0] / 2, 10 * mm, f"Page {doc.page}")
    canvas.drawRightString(A4[0] - 18 * mm, 10 * mm,
                           f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    canvas.restoreState()


def _s(name, **kw):
    base = getSampleStyleSheet()['Normal']
    return ParagraphStyle(name, parent=base, **kw)


# ── shared styles ──────────────────────────────────────────────────────────────
H1     = _s('H1',  fontSize=20, fontName='Helvetica-Bold',  textColor=BLACK,
            alignment=TA_CENTER, spaceAfter=2, spaceBefore=0)
H2     = _s('H2',  fontSize=13, fontName='Helvetica-Bold',  textColor=BLACK,
            alignment=TA_CENTER, spaceAfter=2, spaceBefore=4)
SEC    = _s('SEC', fontSize=10, fontName='Helvetica-Bold',  textColor=colors.white,
            alignment=TA_CENTER, spaceAfter=0, spaceBefore=0,
            backColor=DARK, borderPadding=(4, 8, 4, 8))
SUB    = _s('SUB', fontSize=9,  fontName='Helvetica',       textColor=GREY,
            alignment=TA_CENTER, spaceAfter=2)
WARN   = _s('WARN',fontSize=7,  fontName='Helvetica-Bold',  textColor=RED,
            alignment=TA_CENTER, spaceAfter=4)
BODY   = _s('BODY',fontSize=9,  fontName='Helvetica',       textColor=DARK,
            spaceAfter=3, leading=14, alignment=TA_JUSTIFY)
MONO   = _s('MONO',fontSize=7,  fontName='Courier',         textColor=DARK,
            spaceAfter=3, leading=10, wordWrap='CJK')
LABEL  = _s('LBL', fontSize=8,  fontName='Helvetica-Bold',  textColor=GREY,
            spaceAfter=1)
VAL    = _s('VAL', fontSize=9,  fontName='Helvetica',       textColor=BLACK,
            spaceAfter=4)
OK     = _s('OK',  fontSize=9,  fontName='Helvetica-Bold',  textColor=GREEN,
            spaceAfter=2)
FAIL   = _s('FAIL',fontSize=9,  fontName='Helvetica-Bold',  textColor=RED,
            spaceAfter=2)


def _section_header(story, text):
    story.append(Spacer(1, 6))
    t = Table([[Paragraph(text, SEC)]], colWidths=[174 * mm])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), DARK),
        ('PADDING',    (0, 0), (-1, -1), 6),
        ('ROUNDEDCORNERS', [4]),
    ]))
    story.append(t)
    story.append(Spacer(1, 4))


def _kv_table(story, rows, col_widths=None):
    if col_widths is None:
        col_widths = [40 * mm, 47 * mm, 40 * mm, 47 * mm]
    if len(rows[0]) == 2:
        col_widths = [50 * mm, 124 * mm]

    styled = []
    for row in rows:
        styled_row = []
        for i, cell in enumerate(row):
            is_label = (i % 2 == 0)
            p = Paragraph(str(cell) if cell else '—',
                          _s(f'kv{i}', fontSize=8,
                             fontName='Helvetica-Bold' if is_label else 'Helvetica',
                             textColor=GREY if is_label else BLACK))
            styled_row.append(p)
        styled.append(styled_row)

    t = Table(styled, colWidths=col_widths)
    t.setStyle(TableStyle([
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [LIGHT, colors.white]),
        ('GRID',           (0, 0), (-1, -1), 0.3, MID),
        ('PADDING',        (0, 0), (-1, -1), 5),
        ('VALIGN',         (0, 0), (-1, -1), 'TOP'),
    ]))
    story.append(t)
    story.append(Spacer(1, 4))


def generate_certificate_pdf(
    agreement, landlord, tenant, landlord_cert, tenant_cert,
    qr_image_path, output_path, verification_code,
    landlord_photo_path=None, tenant_photo_path=None,
    en_legal_text: str = '', np_legal_text: str = '',
):
    """Generate professional bilingual (EN + NP) rental certificate PDF."""
    Path(os.path.dirname(output_path)).mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        rightMargin=18 * mm, leftMargin=18 * mm,
        topMargin=16 * mm, bottomMargin=22 * mm,
    )
    story = []

    # ── PAGE 1: COVER / CERTIFICATE HEADER ────────────────────────────────────
    story.append(Spacer(1, 4))
    story.append(Paragraph("VALID RENT AUTHORITY", H1))
    story.append(Paragraph("Secure Rental Verification Certificate", H2))
    story.append(Paragraph("Valid Rent Platform  ·  Academic Prototype  ·  Nepal", SUB))
    story.append(Paragraph(
        "House Rent Act 2053  |  Contract Act 2056  |  Electronic Transactions Act 2063", SUB))
    story.append(Paragraph("⚠  " + WATERMARK_TEXT + "  ⚠", WARN))
    story.append(HRFlowable(width='100%', thickness=2, color=BLACK, spaceAfter=10))

    # ── CERTIFICATE META ───────────────────────────────────────────────────────
    _section_header(story, "CERTIFICATE INFORMATION")
    _kv_table(story, [
        ['Certificate No.', (verification_code or 'N/A'),
         'Agreement ID',    str(agreement.agreement_uid)],
        ['Generated At',    datetime.utcnow().strftime('%d %B %Y, %H:%M UTC'),
         'Status',          (agreement.status or '').upper().replace('_', ' ')],
        ['Rental Category', agreement.rental_category or 'N/A',
         'Rent',            f"{agreement.currency} {agreement.rent_amount or 0:,.2f}"],
        ['Start Date',      str(agreement.start_date or 'N/A'),
         'End Date',        str(agreement.end_date or 'N/A')],
    ])

    # ── ASSET DETAILS ──────────────────────────────────────────────────────────
    _section_header(story, "RENTAL ASSET DETAILS")
    if agreement.asset:
        a = agreement.asset
        _kv_table(story, [
            ['Asset Title',   a.asset_title,
             'Category',      a.category.name if a.category else 'N/A'],
            ['Asset Type',    a.asset_type or 'N/A',
             'Identifier',    a.asset_identifier or 'N/A'],
            ['Location',      a.location or 'N/A',
             'Asking Rent',   f"NPR {a.estimated_value or 0:,.0f} {a.rent_period_label}"],
            ['Description',   (a.description or 'N/A')[:120], '', ''],
        ])
    else:
        _kv_table(story, [['Category', agreement.rental_category or 'N/A', '', '']])

    # ── PARTIES + IDENTITY PHOTOS ─────────────────────────────────────────────
    _section_header(story, "PARTIES & IDENTITY EVIDENCE")

    def _party_block(user, cert, photo_path, sig_ts, cert_serial, role_label):
        items = []
        # Role header
        items.append(Paragraph(role_label, _s('rl', fontSize=9, fontName='Helvetica-Bold',
            textColor=colors.white, backColor=BLACK, alignment=TA_CENTER,
            spaceAfter=4, borderPadding=(3, 6, 3, 6))))
        # Photo
        if photo_path and os.path.exists(photo_path):
            try:
                items.append(RLImage(photo_path, width=26 * mm, height=26 * mm))
            except Exception:
                items.append(Paragraph('[Photo error]', BODY))
        else:
            items.append(Paragraph('[No identity photo captured]', BODY))
        items.append(Paragraph(f"<b>{user.full_name}</b>", BODY))
        items.append(Paragraph(user.email, BODY))
        items.append(Paragraph(f"Phone: {getattr(user, 'phone', None) or 'N/A'}", BODY))
        cert_s = cert.status_display if cert else 'No Certificate'
        cert_n = cert_serial or 'N/A'
        items.append(Paragraph(f"Certificate: {cert_s}", BODY))
        items.append(Paragraph(f"Serial: {cert_n}", MONO))
        if sig_ts:
            items.append(Paragraph("✓  DIGITALLY SIGNED", OK))
            items.append(Paragraph(f"Signed: {sig_ts.strftime('%d %b %Y %H:%M UTC')}", BODY))
        else:
            items.append(Paragraph("✗  NOT YET SIGNED", FAIL))
        return items

    pt = Table([[
        _party_block(landlord, landlord_cert, landlord_photo_path,
                     agreement.landlord_signed_at, agreement.landlord_cert_serial, 'LANDLORD'),
        _party_block(tenant,   tenant_cert,   tenant_photo_path,
                     agreement.tenant_signed_at,   agreement.tenant_cert_serial,   'TENANT'),
    ]], colWidths=[87 * mm, 87 * mm])
    pt.setStyle(TableStyle([
        ('ALIGN',   (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN',  (0, 0), (-1, -1), 'TOP'),
        ('GRID',    (0, 0), (-1, -1), 0.5, MID),
        ('PADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(pt)
    story.append(Spacer(1, 6))

    # ── REMARKS ───────────────────────────────────────────────────────────────
    if agreement.landlord_remarks or agreement.tenant_remarks:
        _section_header(story, "REMARKS AT SIGNING")
        remarks_data = []
        if agreement.landlord_remarks:
            remarks_data.append(['Landlord Remarks', agreement.landlord_remarks])
        if agreement.tenant_remarks:
            remarks_data.append(['Tenant Remarks', agreement.tenant_remarks])
        _kv_table(story, remarks_data, col_widths=[40 * mm, 134 * mm])

    # ── SPECIAL TERMS ─────────────────────────────────────────────────────────
    if agreement.terms:
        _section_header(story, "SPECIAL TERMS & CONDITIONS")
        story.append(Paragraph(agreement.terms, BODY))
        story.append(Spacer(1, 4))

    # ── DIGITAL SIGNATURES ────────────────────────────────────────────────────
    _section_header(story, "DIGITAL SIGNATURES (RSA-2048)")
    story.append(Paragraph(
        "Each signature below is an RSA-2048 cryptographic proof generated from the signer's "
        "private key against the SHA-256 hash of this document. Verification can be performed "
        "using the signer's public key stored on the Valid Rent platform.", BODY))
    story.append(Spacer(1, 4))

    l_ok = agreement.landlord_signature is not None
    t_ok = agreement.tenant_signature is not None
    sig_status_data = [
        ['Party',     'Status',
         'Certificate Serial',                  'Signed At'],
        ['Landlord',  '✓ SIGNED' if l_ok else '✗ NOT SIGNED',
         agreement.landlord_cert_serial or 'N/A',
         agreement.landlord_signed_at.strftime('%d %b %Y %H:%M') if agreement.landlord_signed_at else '—'],
        ['Tenant',    '✓ SIGNED' if t_ok else '✗ NOT SIGNED',
         agreement.tenant_cert_serial or 'N/A',
         agreement.tenant_signed_at.strftime('%d %b %Y %H:%M') if agreement.tenant_signed_at else '—'],
    ]
    t = Table(sig_status_data, colWidths=[28 * mm, 28 * mm, 78 * mm, 40 * mm])
    t.setStyle(TableStyle([
        ('BACKGROUND',  (0, 0), (-1, 0),   DARK),
        ('TEXTCOLOR',   (0, 0), (-1, 0),   colors.white),
        ('FONTNAME',    (0, 0), (-1, 0),   'Helvetica-Bold'),
        ('FONTSIZE',    (0, 0), (-1, -1),  8),
        ('FONTNAME',    (0, 1), (-1, -1),  'Helvetica'),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [LIGHT, colors.white]),
        ('GRID',        (0, 0), (-1, -1),  0.3, MID),
        ('PADDING',     (0, 0), (-1, -1),  5),
        ('ALIGN',       (0, 0), (-1, -1),  'LEFT'),
    ]))
    story.append(t)
    story.append(Spacer(1, 6))

    # Full signature values
    if agreement.landlord_signature:
        story.append(Paragraph("Landlord RSA-2048 Signature:", LABEL))
        story.append(Paragraph(agreement.landlord_signature, MONO))
    if agreement.tenant_signature:
        story.append(Paragraph("Tenant RSA-2048 Signature:", LABEL))
        story.append(Paragraph(agreement.tenant_signature, MONO))

    # ── CRYPTOGRAPHIC INTEGRITY ───────────────────────────────────────────────
    _section_header(story, "CRYPTOGRAPHIC INTEGRITY")
    story.append(Paragraph("Document SHA-256 Hash:", LABEL))
    story.append(Paragraph(agreement.document_hash_sha256 or 'N/A', MONO))
    final_label = ("✓  FULLY VERIFIED — BOTH PARTIES SIGNED"
                   if agreement.is_fully_signed
                   else "⏳  PENDING — SIGNATURES INCOMPLETE")
    story.append(Paragraph(final_label, OK if agreement.is_fully_signed else FAIL))
    story.append(Spacer(1, 6))

    # ── QR CODE ───────────────────────────────────────────────────────────────
    _section_header(story, "ONLINE VERIFICATION")
    qr_inner = [Paragraph("Scan the QR code to verify this certificate online:", BODY)]
    if qr_image_path and os.path.exists(qr_image_path):
        try:
            qr_inner.append(RLImage(qr_image_path, width=34 * mm, height=34 * mm))
        except Exception:
            pass
    qr_inner.append(Paragraph(f"Verify URL: /verify/code/{verification_code}", MONO))
    qr_t = Table([qr_inner], colWidths=[174 * mm])
    qr_t.setStyle(TableStyle([
        ('ALIGN',   (0, 0), (-1, -1), 'CENTER'),
        ('PADDING', (0, 0), (-1, -1), 8),
        ('BOX',     (0, 0), (-1, -1), 0.5, MID),
    ]))
    story.append(qr_t)
    story.append(Spacer(1, 8))

    # ── FOOTER DISCLAIMER (page 1) ────────────────────────────────────────────
    story.append(HRFlowable(width='100%', thickness=1, color=MID, spaceAfter=4))
    story.append(Paragraph(DISCLAIMER, _s('disc', fontSize=7, fontName='Helvetica-Oblique',
                                          textColor=GREY, alignment=TA_CENTER)))

    # ── PAGE 2: ENGLISH LEGAL TEXT ────────────────────────────────────────────
    if en_legal_text:
        story.append(PageBreak())
        story.append(Paragraph("VALID RENT — RENTAL AGREEMENT", H1))
        story.append(Paragraph("Full Legal Text — English", H2))
        story.append(HRFlowable(width='100%', thickness=2, color=BLACK, spaceAfter=8))
        for line in en_legal_text.split('\n'):
            stripped = line.rstrip()
            if stripped.startswith('━'):
                story.append(HRFlowable(width='100%', thickness=0.5, color=MID, spaceAfter=2, spaceBefore=4))
            elif stripped.isupper() and len(stripped) > 4:
                story.append(Paragraph(stripped, _s('bold_line', fontSize=9,
                    fontName='Helvetica-Bold', textColor=DARK, spaceAfter=2)))
            else:
                story.append(Paragraph(stripped or '&nbsp;', BODY))

    # ── PAGE 3: NEPALI LEGAL TEXT ─────────────────────────────────────────────
    if np_legal_text:
        story.append(PageBreak())
        story.append(Paragraph("भ्यालिड रेन्ट — भाडा सम्झौता", H1))
        story.append(Paragraph("पूर्ण कानूनी पाठ — नेपाली", H2))
        story.append(HRFlowable(width='100%', thickness=2, color=BLACK, spaceAfter=8))
        for line in np_legal_text.split('\n'):
            stripped = line.rstrip()
            if stripped.startswith('━'):
                story.append(HRFlowable(width='100%', thickness=0.5, color=MID, spaceAfter=2, spaceBefore=4))
            else:
                story.append(Paragraph(stripped or '&nbsp;', BODY))

    doc.build(story, onFirstPage=_page_footer, onLaterPages=_page_footer)
    return hashlib.sha256(open(output_path, 'rb').read()).hexdigest()
