import os
import hashlib
from datetime import datetime
from pathlib import Path

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, Image as RLImage, PageBreak, KeepTogether
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont

WATERMARK_TEXT = "ACADEMIC PROTOTYPE – NOT AN OFFICIAL GOVERNMENT DOCUMENT"
DISCLAIMER = (
    "This document is generated by the Valid Rent Academic Prototype Platform. "
    "It is NOT affiliated with, endorsed by, or operated by the Government of Nepal. "
    "Any government-style design is used solely for educational demonstration purposes."
)


def _add_watermark(canvas, doc):
    canvas.saveState()
    canvas.setFont('Helvetica-Bold', 20)
    canvas.setFillColorRGB(0.87, 0.87, 0.87)
    canvas.translate(A4[0] / 2, A4[1] / 2)
    canvas.rotate(45)
    canvas.drawCentredString(0, 0, WATERMARK_TEXT)
    canvas.restoreState()


def _page_footer(canvas, doc):
    _add_watermark(canvas, doc)
    canvas.saveState()
    canvas.setFont('Helvetica', 7)
    canvas.setFillColor(colors.grey)
    canvas.drawString(20 * mm, 10 * mm,
                      f"Valid Rent Platform — Academic Prototype | Page {doc.page}")
    canvas.drawRightString(A4[0] - 20 * mm, 10 * mm,
                           f"Generated: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    canvas.restoreState()


def generate_certificate_pdf(
    agreement, landlord, tenant, landlord_cert, tenant_cert,
    qr_image_path, output_path, verification_code,
    landlord_photo_path=None, tenant_photo_path=None,
    en_legal_text: str = '', np_legal_text: str = '',
):
    """Generate official-style bilingual (EN + NP) PDF verification certificate."""
    Path(os.path.dirname(output_path)).mkdir(parents=True, exist_ok=True)

    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        rightMargin=18 * mm, leftMargin=18 * mm,
        topMargin=18 * mm, bottomMargin=22 * mm,
    )

    styles = getSampleStyleSheet()

    def style(name, **kw):
        s = ParagraphStyle(name, parent=styles['Normal'], **kw)
        return s

    h1 = style('H1', fontSize=18, fontName='Helvetica-Bold',
                textColor=colors.black, alignment=TA_CENTER, spaceAfter=4)
    h2 = style('H2', fontSize=13, fontName='Helvetica-Bold', spaceAfter=4, spaceBefore=10)
    sub = style('Sub', fontSize=9, fontName='Helvetica',
                textColor=colors.grey, alignment=TA_CENTER, spaceAfter=2)
    warn = style('Warn', fontSize=7, fontName='Helvetica-Bold',
                 textColor=colors.red, alignment=TA_CENTER, spaceAfter=6)
    body = style('Body', fontSize=9, fontName='Helvetica',
                 textColor=colors.black, spaceAfter=4, leading=14)
    mono = style('Mono', fontSize=7, fontName='Courier',
                 textColor=colors.darkblue, spaceAfter=4, leading=10, wordWrap='CJK')

    story = []

    # ── COVER / HEADER ──────────────────────────────────────────────────────
    story.append(Paragraph("⬡  VALID RENT AUTHORITY DEMO SEAL  ⬡", h1))
    story.append(Paragraph("Secure Rental Verification Certificate", style(
        'TitleSub', fontSize=15, fontName='Helvetica-Bold',
        textColor=colors.black, alignment=TA_CENTER, spaceAfter=2)))
    story.append(Paragraph("Valid Rent Platform · Academic Prototype · Nepal", sub))
    story.append(Paragraph(WATERMARK_TEXT, warn))
    story.append(HRFlowable(width='100%', thickness=2, color=colors.black, spaceAfter=12))

    # ── CERT META ───────────────────────────────────────────────────────────
    cert_data = [
        ['Certificate No.', (verification_code or '')[:20] + '…',
         'Agreement ID', str(agreement.agreement_uid)[:18] + '…'],
        ['Generated At', datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC'),
         'Status', (agreement.status or '').upper()],
        ['Rental Category', agreement.rental_category or 'N/A',
         'Rent/Month', f"{agreement.currency} {agreement.rent_amount or 0:,.2f}"],
        ['Start Date', str(agreement.start_date or 'N/A'),
         'End Date', str(agreement.end_date or 'N/A')],
    ]
    _meta_table(story, cert_data)
    story.append(Spacer(1, 8))

    # ── ASSET ───────────────────────────────────────────────────────────────
    story.append(Paragraph("▸ RENTAL ASSET DETAILS", h2))
    if agreement.asset:
        a = agreement.asset
        asset_data = [
            ['Asset Title', a.asset_title, 'Category', a.category.name if a.category else 'N/A'],
            ['Type', a.asset_type or 'N/A', 'Identifier', a.asset_identifier or 'N/A'],
            ['Location', a.location or 'N/A', 'Est. Value', f"NPR {a.estimated_value or 0:,.0f}"],
        ]
    else:
        asset_data = [['Category', agreement.rental_category or 'N/A', '', '']]
    _meta_table(story, asset_data)
    story.append(Spacer(1, 8))

    # ── PARTIES + PHOTOS ────────────────────────────────────────────────────
    story.append(Paragraph("▸ PARTIES WITH IDENTITY EVIDENCE", h2))

    def _party_col(user, cert, photo_path, sig, role_label):
        col = [Paragraph(role_label, style(
            'RL', fontSize=9, fontName='Helvetica-Bold',
            textColor=colors.white, alignment=TA_CENTER,
            backColor=colors.black, spaceAfter=4))]
        # Photo
        if photo_path and os.path.exists(photo_path):
            try:
                col.append(RLImage(photo_path, width=28 * mm, height=28 * mm))
            except Exception:
                col.append(Paragraph('[Photo error]', body))
        else:
            col.append(Paragraph('[No photo captured]', body))
        col.append(Paragraph(f"<b>{user.full_name}</b>", body))
        col.append(Paragraph(user.email, body))
        col.append(Paragraph(f"Phone: {user.phone or 'N/A'}", body))
        cert_status = cert.status_display if cert else 'N/A'
        cert_serial = (cert.serial_number[:12] + '…') if cert else 'N/A'
        col.append(Paragraph(f"Cert: {cert_status} | {cert_serial}", mono))
        signed_at = sig.strftime('%Y-%m-%d %H:%M') if sig else 'Not signed'
        sig_status = '✓ SIGNED' if sig else '✗ NOT SIGNED'
        col.append(Paragraph(f"Signature: {sig_status}", body))
        col.append(Paragraph(f"Signed at: {signed_at}", body))
        return col

    parties_data = [[
        _party_col(landlord, landlord_cert, landlord_photo_path,
                   agreement.landlord_signed_at, 'LANDLORD'),
        _party_col(tenant, tenant_cert, tenant_photo_path,
                   agreement.tenant_signed_at, 'TENANT'),
    ]]
    pt = Table(parties_data, colWidths=[87 * mm, 87 * mm])
    pt.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('GRID', (0, 0), (-1, -1), 0.3, colors.lightgrey),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(pt)
    story.append(Spacer(1, 8))

    # ── SIGNATURE STATUS ────────────────────────────────────────────────────
    story.append(Paragraph("▸ DIGITAL SIGNATURE STATUS", h2))
    l_ok = '✓ SIGNED' if agreement.landlord_signature else '✗ NOT SIGNED'
    t_ok = '✓ SIGNED' if agreement.tenant_signature else '✗ NOT SIGNED'
    sig_data = [
        ['Party', 'Status', 'Certificate Serial', 'Signed At'],
        ['Landlord', l_ok,
         (agreement.landlord_cert_serial or 'N/A')[:16] + '…',
         str(agreement.landlord_signed_at or 'N/A')],
        ['Tenant', t_ok,
         (agreement.tenant_cert_serial or 'N/A')[:16] + '…',
         str(agreement.tenant_signed_at or 'N/A')],
    ]
    _meta_table(story, sig_data, header=True)
    story.append(Spacer(1, 8))

    # ── CRYPTO INTEGRITY ────────────────────────────────────────────────────
    story.append(Paragraph("▸ CRYPTOGRAPHIC INTEGRITY", h2))
    story.append(Paragraph(f"Document SHA-256 Hash:", style(
        'HashLabel', fontSize=8, fontName='Helvetica-Bold', spaceAfter=2)))
    story.append(Paragraph(agreement.document_hash_sha256 or 'N/A', mono))
    final = 'VERIFIED — BOTH PARTIES SIGNED' if agreement.is_fully_signed else 'PENDING SIGNATURES'
    story.append(Paragraph(f"Final Verification: {final}", style(
        'FV', fontSize=11, fontName='Helvetica-Bold', spaceAfter=4,
        textColor=colors.HexColor('#15803d') if agreement.is_fully_signed else colors.HexColor('#92400e'))))
    story.append(Spacer(1, 6))

    # ── QR CODE ─────────────────────────────────────────────────────────────
    qr_row = [[]]
    qr_row[0].append(Paragraph("Scan to verify online:", body))
    if qr_image_path and os.path.exists(qr_image_path):
        try:
            qr_row[0].append(RLImage(qr_image_path, width=32 * mm, height=32 * mm))
        except Exception:
            pass
    qr_row[0].append(Paragraph(f"Verify URL: /verify/code/{verification_code}", mono))
    qr_t = Table(qr_row, colWidths=[174 * mm])
    qr_t.setStyle(TableStyle([
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('GRID', (0, 0), (-1, -1), 0.3, colors.lightgrey),
        ('PADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(qr_t)
    story.append(Spacer(1, 10))

    # ── BILINGUAL LEGAL TEXT ─────────────────────────────────────────────────
    if en_legal_text or np_legal_text:
        story.append(PageBreak())
        story.append(Paragraph("▸ LEGAL AGREEMENT TEXT — ENGLISH", h2))
        story.append(HRFlowable(width='100%', thickness=1, color=colors.black, spaceAfter=6))
        for line in (en_legal_text or '').split('\n'):
            story.append(Paragraph(line or '&nbsp;', body))

        story.append(PageBreak())
        story.append(Paragraph("▸ कानूनी सम्झौता पाठ — नेपाली", h2))
        story.append(HRFlowable(width='100%', thickness=1, color=colors.black, spaceAfter=6))
        # Nepali text as-is (ASCII fallback for Devanagari in basic PDF)
        for line in (np_legal_text or '').split('\n'):
            story.append(Paragraph(line or '&nbsp;', body))

    # ── FOOTER DISCLAIMER ────────────────────────────────────────────────────
    story.append(Spacer(1, 10))
    story.append(HRFlowable(width='100%', thickness=1, color=colors.black, spaceAfter=6))
    story.append(Paragraph(DISCLAIMER, style(
        'Disc', fontSize=7, fontName='Helvetica-Oblique',
        textColor=colors.grey, alignment=TA_CENTER)))

    doc.build(story, onFirstPage=_page_footer, onLaterPages=_page_footer)

    return hashlib.sha256(open(output_path, 'rb').read()).hexdigest()


def _meta_table(story, data, header=False):
    col_widths = [38 * mm, 52 * mm, 38 * mm, 46 * mm]
    if len(data[0]) == 2:
        col_widths = [50 * mm, 124 * mm]

    t = Table(data, colWidths=col_widths)
    ts = [
        ('FONTNAME', (0, 0), (-1, -1), 'Helvetica'),
        ('FONTSIZE', (0, 0), (-1, -1), 8),
        ('ROWBACKGROUNDS', (0, 0), (-1, -1), [colors.whitesmoke, colors.white]),
        ('GRID', (0, 0), (-1, -1), 0.3, colors.lightgrey),
        ('PADDING', (0, 0), (-1, -1), 4),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]
    if header:
        ts += [
            ('BACKGROUND', (0, 0), (-1, 0), colors.black),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ]
    else:
        # Bold label columns
        ts += [
            ('FONTNAME', (0, 0), (0, -1), 'Helvetica-Bold'),
            ('FONTNAME', (2, 0), (2, -1), 'Helvetica-Bold'),
        ]
    t.setStyle(TableStyle(ts))
    story.append(t)
