name: ValidRent CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Install Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      # Step 3: Install project dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Step 4: Run the tests
      - name: Run tests
        run: pytest tests/ -v
